language: rust

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

matrix:
  include:
    - os: linux
      rust: nightly

script:
    - rustup component add llvm-tools-preview
    - rustup component add clippy-preview
    - export RUSTFLAGS="-Zinstrument-coverage"
    - cargo build --verbose
    - cargo clippy
    - LLVM_PROFILE_FILE="bank_payments_system-%p-%m.profraw" cargo test --verbose
    - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - bash <(curl -s https://codecov.io/bash) -f lcov.info